export const NEW_BOOKING_REQUEST = 'NEW_BOOKING_REQUEST';
export const NEW_BOOKING_SUCCESS = 'NEW_BOOKING_SUCCESS';
export const NEW_BOOKING_RESET = 'NEW_BOOKING_RESET';
export const NEW_BOOKING_FAIL = 'NEW_BOOKING_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';